/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 scene.gltf
Author: Wayne Pearce (https://sketchfab.com/WaynePearce10)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-galaxy-simulation-58e7b5996f674caeaa3ec2c9df371212
Title: Simple Galaxy Simulation
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Scene(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group name="Sphere002" rotation={[Math.PI / 2, 0.01, 0]} scale={2.14}>
              <mesh name="Sphere002_0" geometry={nodes.Sphere002_0.geometry} material={materials.Root} />
            </group>
            <group name="Lamp" position={[4.08, 1.01, 5.9]} rotation={[-0.27, 0.6, 1.93]}>
              <group name="Lamp_1" />
            </group>
            <group name="Sphere" scale={5}>
              <mesh name="Sphere_0" geometry={nodes.Sphere_0.geometry} material={materials.Root} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
export default Scene;